# PLN — Coleta e pré-processamento de receitas do TudoGostoso

**Equipe:** Alana Cristina Andreazza, Beatriz Moresco Joaquim, Caio Abraão, Haiko Rudiger e Leticia Fruet

O notebook realiza duas etapas principais:

1. coleta das receitas do TudoGostoso;
2. pré-processamento textual seguindo a estrutura apresentada pelo professor.

A base mantém os campos estruturados de cada receita e cria também um único campo textual para aplicação do pipeline de PLN.

## 1. Preparação do ambiente

Para a coleta são utilizados `requests` e `BeautifulSoup`.  
Para o pré-processamento, seguimos as bibliotecas utilizadas no notebook do professor:

- **NLTK**: tokenização, stopwords e stemming;
- **spaCy**: lematização;
- **Pandas**: organização dos dados.

In [ ]:
%pip -q install requests beautifulsoup4 pandas nltk spacy

In [ ]:
import re
import subprocess
import sys
import time

import nltk
import pandas as pd
import requests
import spacy

from bs4 import BeautifulSoup
from nltk.corpus import stopwords
from nltk.stem import RSLPStemmer
from nltk.tokenize import word_tokenize
from urllib.parse import urljoin

for recurso in ["punkt", "punkt_tab", "stopwords", "rslp"]:
    nltk.download(recurso, quiet=True)

try:
    nlp = spacy.load("pt_core_news_sm")
except OSError:
    subprocess.run(
        [sys.executable, "-m", "spacy", "download", "pt_core_news_sm"],
        check=True,
    )
    nlp = spacy.load("pt_core_news_sm")

print("Ambiente preparado com sucesso.")

Ambiente preparado com sucesso.

## 2. Categorias utilizadas

Foram mantidas as categorias definidas pelo grupo para obter variedade de receitas.

In [ ]:
BASE_URL = "https://www.tudogostoso.com.br"

CATEGORIAS = [
    {"categoria": "BOLOS E TORTAS", "url": "https://www.tudogostoso.com.br/categorias/1000-bolos-e-tortas-doces"},
    {"categoria": "CARNES", "url": "https://www.tudogostoso.com.br/categorias/1004-carnes"},
    {"categoria": "AVES", "url": "https://www.tudogostoso.com.br/categorias/1009-aves"},
    {"categoria": "PEIXES E FRUTOS DO MAR", "url": "https://www.tudogostoso.com.br/categorias/1014-peixes-e-frutos-do-mar"},
    {"categoria": "SALADAS E MOLHOS", "url": "https://www.tudogostoso.com.br/categorias/1023-saladas-molhos-e-acompanhamentos"},
    {"categoria": "SOPAS", "url": "https://www.tudogostoso.com.br/categorias/1027-sopas"},
    {"categoria": "MASSAS", "url": "https://www.tudogostoso.com.br/categorias/1028-massas"},
    {"categoria": "BEBIDAS", "url": "https://www.tudogostoso.com.br/categorias/1032-bebidas"},
    {"categoria": "DOCES E SOBREMESAS", "url": "https://www.tudogostoso.com.br/categorias/1037-doces-e-sobremesas"},
    {"categoria": "LANCHES", "url": "https://www.tudogostoso.com.br/categorias/1044-lanches"},
    {"categoria": "ALIMENTAÇÃO SAUDÁVEL", "url": "https://www.tudogostoso.com.br/categorias/1334-alimentacao-saudavel"},
]

LIMITE_RECEITAS_POR_CATEGORIA = 15

## 3. Acesso às páginas

A estrutura anterior dependia de caminhos CSS longos e de posições como `nth-child`.  
Isso tornava a coleta sensível a pequenas mudanças no HTML.

Nesta versão, a extração usa principalmente classes e seções semânticas da página.  
A versão AMP oficial da mesma receita é usada somente como apoio para campos que podem não estar presentes de forma estável no HTML principal, como avaliação, dificuldade e custo.

In [ ]:
sessao = requests.Session()
sessao.headers.update({
    "User-Agent": "FURB-PLN-AvaliacaoPratica1/1.0 (uso academico)",
    "Accept-Language": "pt-BR,pt;q=0.9",
})


def obter_soup(url):
    try:
        resposta = sessao.get(url, timeout=20)
        resposta.raise_for_status()
        return BeautifulSoup(resposta.content, "html.parser")
    except requests.RequestException as erro:
        print(f"Erro ao acessar {url}: {erro}")
        return None


def url_amp(url):
    return url.replace(
        "https://www.tudogostoso.com.br/",
        "https://amp.tudogostoso.com.br/"
    )

## 4. Localização das receitas nas categorias

Primeiro reunimos os links de todas as categorias.

A URL é usada como identificador da receita. Se a mesma URL aparecer em duas ou mais categorias, ela permanece uma única vez e o campo `Categorias` recebe todas as categorias correspondentes.

In [ ]:
SELETOR_TITULOS_RECEITAS = (
    "#main-content div.mg-container.gd-2-cols div.left-col "
    "section.u-margin-top.u-padding-top.u-padding-bottom "
    "div.card-content h2 a"
)


def extrair_receitas_categoria(categoria, url_categoria, limite=None):
    soup = obter_soup(url_categoria)

    if soup is None:
        return []

    elementos = soup.select(SELETOR_TITULOS_RECEITAS)

    if limite is not None:
        elementos = elementos[:limite]

    return [
        {
            "Título": elemento.get_text(" ", strip=True),
            "URL da receita": urljoin(
                BASE_URL,
                elemento.get("href", "")
            ),
            "Categoria": categoria,
        }
        for elemento in elementos
        if elemento.get("href")
    ]


receitas_por_url = {}

for categoria in CATEGORIAS:
    encontradas = extrair_receitas_categoria(
        categoria["categoria"],
        categoria["url"],
        LIMITE_RECEITAS_POR_CATEGORIA,
    )

    for receita in encontradas:
        url = receita["URL da receita"]

        if url not in receitas_por_url:
            receitas_por_url[url] = {
                "Título": receita["Título"],
                "URL da receita": url,
                "Categorias": [],
            }

        if receita["Categoria"] not in receitas_por_url[url]["Categorias"]:
            receitas_por_url[url]["Categorias"].append(
                receita["Categoria"]
            )

print("Receitas únicas encontradas:", len(receitas_por_url))

Receitas únicas encontradas: 159

## 5. Extração dos dados da receita

- ingredientes são procurados dentro de `section.recipe-ingredients`;
- utensílios dentro de `section.recipe-equipments`;
- etapas são localizadas pelos IDs que começam com `recipe-step`;
- porções são obtidas pelo título da seção de ingredientes;
- avaliação, quantidade de avaliações, dificuldade e custo possuem fallback pela página AMP oficial.

In [ ]:
def texto_elemento(elemento):
    return elemento.get_text(" ", strip=True) if elemento else None


def limpar_texto_utensilio(texto):
    if not texto:
        return None

    texto = re.sub(r"\bComprar\b", "", texto, flags=re.IGNORECASE)
    texto = re.sub(r"\s+", " ", texto).strip()
    return texto or None


def extrair_porcoes(soup):
    secao = soup.select_one("section.recipe-ingredients")

    if secao:
        titulo = secao.find(["h1", "h2", "h3"])
        if titulo:
            texto = titulo.get_text(" ", strip=True)
            resultado = re.search(
                r"(\d+\s+porç(?:ão|ões))",
                texto,
                flags=re.IGNORECASE,
            )
            if resultado:
                return resultado.group(1)

    return None


def extrair_ingredientes(soup):
    secao = soup.select_one("section.recipe-ingredients")

    if not secao:
        return []

    ingredientes = []

    for item in secao.select("li"):
        texto = item.get_text(" ", strip=True)

        if texto:
            ingredientes.append(texto)

    return ingredientes


def extrair_utensilios(soup):
    secao = soup.select_one("section.recipe-equipments")

    if not secao:
        return []

    utensilios = []

    for item in secao.select("li"):
        texto = limpar_texto_utensilio(
            item.get_text(" ", strip=True)
        )

        if texto:
            utensilios.append(texto)

    return utensilios


def extrair_etapas(soup):
    etapas = []

    for elemento in soup.select('[id^="recipe-step"] p'):
        texto = elemento.get_text(" ", strip=True)

        if texto and texto not in etapas:
            etapas.append(texto)

    return etapas


def extrair_tempo(soup):
    # Primeiro tenta o bloco de informações da receita.
    for bloco in soup.select(".recipe-info > div"):
        texto = bloco.get_text(" ", strip=True)
        if "min" in texto.lower():
            return texto

    # Fallback para o texto exibido na área "Modo de preparo".
    texto_pagina = soup.get_text(" ", strip=True)
    resultado = re.search(
        r"Modo de preparo\s*:\s*(\d+\s*min)",
        texto_pagina,
        flags=re.IGNORECASE,
    )

    return resultado.group(1) if resultado else None


def extrair_metadados_amp(soup_amp):
    dados = {
        "Nível de dificuldade": None,
        "Custo": None,
        "Avaliação": None,
        "Quantidade de avaliações": None,
    }

    if soup_amp is None:
        return dados

    texto = soup_amp.get_text(" ", strip=True)

    avaliacao = re.search(
        r"(\d+(?:[.,]\d+)?)\s*/\s*5",
        texto,
        flags=re.IGNORECASE,
    )
    if avaliacao:
        dados["Avaliação"] = avaliacao.group(1).replace(",", ".")

    quantidade = re.search(
        r"\(\s*([\d.,]+(?:\s*[KkMm])?)\s+avaliaç(?:ão|ões)\s*\)",
        texto,
        flags=re.IGNORECASE,
    )
    if quantidade:
        dados["Quantidade de avaliações"] = quantidade.group(1)

    dificuldade = re.search(
        r"\b(Muito fácil|Fácil|Médio|Média|Difícil|Muito difícil)\b",
        texto,
        flags=re.IGNORECASE,
    )
    if dificuldade:
        dados["Nível de dificuldade"] = dificuldade.group(1)

    custo = re.search(
        r"\b(Custo\s+(?:baixo|médio|alto))\b",
        texto,
        flags=re.IGNORECASE,
    )
    if custo:
        dados["Custo"] = custo.group(1)

    return dados


def extrair_dados_receita(receita):
    url = receita["URL da receita"]

    soup = obter_soup(url)

    if soup is None:
        return None

    # Campos principais do HTML da receita.
    porcoes = extrair_porcoes(soup)
    ingredientes = extrair_ingredientes(soup)
    utensilios = extrair_utensilios(soup)
    etapas = extrair_etapas(soup)
    tempo = extrair_tempo(soup)

    # Alguns campos podem estar ausentes no HTML principal.
    soup_amp = obter_soup(url_amp(url))
    metadados_amp = extrair_metadados_amp(soup_amp)

    return {
        "Categorias": receita["Categorias"],
        "Título": receita["Título"],
        "URL da receita": url,
        "Tempo de preparo": tempo,
        "Nível de dificuldade": metadados_amp["Nível de dificuldade"],
        "Custo": metadados_amp["Custo"],
        "Porções": porcoes,
        "Ingredientes": ingredientes,
        "Utensílios": utensilios,
        "Etapas do preparo": etapas,
        "Avaliação": metadados_amp["Avaliação"],
        "Quantidade de avaliações": metadados_amp["Quantidade de avaliações"],
    }

## 6. Executar a coleta

Cada URL é processada somente uma vez, mesmo que a receita pertença a várias categorias.

In [ ]:
resultados = []

for numero, receita in enumerate(receitas_por_url.values(), start=1):
    print(f"{numero}. Processando: {receita['Título']}")

    dados = extrair_dados_receita(receita)

    if dados is not None:
        resultados.append(dados)

    time.sleep(1)

df_receitas = pd.DataFrame(resultados)

print("\nReceitas armazenadas:", len(df_receitas))
display(df_receitas.head(10))

1. Processando: Bolo de milho de lata no liquidificador
2. Processando: Bolo de fubá simples
3. Processando: Brownie simples e rápido
4. Processando: Bolo simples
5. Processando: Bolo de caneca micro-ondas
6. Processando: Bolo de laranja
7. Processando: Bolo pão-de-ló tradicional
8. Processando: Bolo de laranja de liquidificador
9. Processando: Bolo de iogurte
10. Processando: Pavê de chocolate
11. Processando: Bolo de fubá cremoso
12. Processando: Bolo flocão
13. Processando: Bolo de liquidificador
14. Processando: Bolo de coco gelado
15. Processando: Bolo de maçã de liquidificador - o melhor do mundo
16. Processando: Carne de panela de pressão
17. Processando: Rocambole de carne moída maravilhoso
18. Processando: Yakissoba da casa
19. Processando: Strogonoff de carne
20. Processando: Bife à milanesa
21. Processando: Escondidinho de carne-seca
22. Processando: Almôndegas
23. Processando: Arroz de forno à parmegiana
24. Processando: Quibe fácil
25. Processando: Costela na panela de pressão sem água
26. Processando: Batata suíça
27. Processando: Costela de boi na panela de pressão cozida na cebola
28. Processando: Bife à parmegiana
29. Processando: Filé de frango à parmegiana
30. Processando: Carne assada na panela de pressão
31. Processando: Gratinado de frango simples
32. Processando: Frango cremoso
33. Processando: Frango com Catupiri e batata palha da tia Gracia
34. Processando: Salpicão
35. Processando: Estrogonofe da casa
36. Processando: Frango assado inteiro e descomplicado
37. Processando: Estrogonofe de frango simples
38. Processando: Estrogonofe de frango básico
39. Processando: Filé de frango à milanesa
40. Processando: Frango com quiabo mineiro
41. Processando: Frango à passarinho super crocante
42. Processando: Frango assado com creme de cebola e maionese
43. Processando: Fricassê de frango
44. Processando: Frango frito americano
45. Processando: Bobó de camarão
46. Processando: Filé de peixe assado
47. Processando: Camarão na moranga
48. Processando: Almoço rápido
49. Processando: Bolinho de bacalhau
50. Processando: Filé de merluza com batata ao forno
51. Processando: Moqueca de peixe
52. Processando: Estrogonofe de camarão
53. Processando: Filé de salmão ao forno facílimo
54. Processando: Filé de peixe da mamãe
55. Processando: Moqueca de camarão
56. Processando: Sardinha na panela de pressão
57. Processando: Peixe ao leite de coco
58. Processando: Bacalhoada
59. Processando: Camarão com requeijão
60. Processando: Creme de milho
61. Processando: Molho branco para macarrão
62. Processando: Bolinho de arroz
63. Processando: Arroz de forma
64. Processando: Frango ao creme de milho
65. Processando: Escondidinho de carne moída
66. Processando: Molho branco
67. Processando: Arroz à grega
68. Processando: Molho branco simples
69. Processando: Cuscuz paulista
70. Processando: Risoto de camarão
71. Processando: Costelinha com molho barbecue (outback)
72. Processando: Caldo verde
73. Processando: Torta cremosa de frango
74. Processando: Canja de galinha rápida
75. Processando: Macarrão com requeijão
76. Processando: Sopa de feijão
77. Processando: Macarrão ao forno com bacon e mussarela
78. Processando: Caldo verde
79. Processando: Sopa de Cebola
80. Processando: Caldinho de mandioca
81. Processando: Torta salgada de frango
82. Processando: Feijão tropeiro
83. Processando: Sopa de legumes com macarrão
84. Processando: Torta de frango com creme de leite e mussarela
85. Processando: Pudim de Abacaxi
86. Processando: Panqueca de carne moída
87. Processando: Pão caseiro
88. Processando: Panquecas (receita da vovó)
89. Processando: Pão caseiro rápido e fofo
90. Processando: Panqueca americana
91. Processando: Lasanha de carne moída
92. Processando: Pão segura marido
93. Processando: Massa de panqueca simples
94. Processando: Massa de panqueca
95. Processando: Pão de queijo 3 ingredientes
96. Processando: Nhoque fácil
97. Processando: Pão de queijo
98. Processando: Panqueca
99. Processando: Nhoque de batata
100. Processando: Pão caseiro fácil
101. Processando: Chocolate quente cremoso
102. Processando: Chocolate quente especial
103. Processando: Cappuccino fácil
104. Processando: Milk shake de chocolate
105. Processando: Cappuccino caseiro
106. Processando: Milk shake (ovomaltine original)
107. Processando: Chocolate quente sem leite ou leite condensado
108. Processando: Limonada Suíça
109. Processando: Quentão
110. Processando: Creme de café (café cremoso)
111. Processando: Batida de Sonho de Valsa
112. Processando: Suco de couve com limão
113. Processando: Vinho quente
114. Processando: Nevada
115. Processando: Capuccino caseiro
116. Processando: Pudim de leite condensado simples
117. Processando: Danoninho caseiro
118. Processando: Mousse de limão rápido
119. Processando: Brigadeirão rápido e fácil
120. Processando: Doce gelado de coco com chocolate
121. Processando: Mousse de maracujá
122. Processando: Bolo de milho cremoso
123. Processando: Mousse de limão
124. Processando: Arroz doce verdadeiro
125. Processando: Mousse de maracujá fácil
126. Processando: Pavê de Bis
127. Processando: Brigadeirão
128. Processando: Mousse de chocolate
129. Processando: Petit gateau
130. Processando: Torta de limão
131. Processando: Torta de liquidificador
132. Processando: Bolinho de chuva
133. Processando: Torta de frango de liquidificador deliciosa e fácil
134. Processando: Pipoca doce
135. Processando: Bolinho de chuva
136. Processando: Coxinha prática deliciosa
137. Processando: Misto quente de forno à minha moda
138. Processando: Cookie americano perfeito
139. Processando: Bolinha de queijo
140. Processando: Biscoito de maisena
141. Processando: Pastel de forno
142. Processando: Biscoitos amanteigados
143. Processando: Joelho
144. Processando: Bolinhos de chuva
145. Processando: Bolo integral de banana
146. Processando: Tabule
147. Processando: Crepe de tapioca (crepioca)
148. Processando: Crepioca - Pão de queijo de frigideira
149. Processando: Torta integral de atum
150. Processando: Crepioca fit
151. Processando: Pão sem glúten de liquidificador
152. Processando: Picolé salada de frutas
153. Processando: Bolo fácil de laranja sem glúten
154. Processando: Panqueca saudável de aveia e banana
155. Processando: Coxinha fit (pré-treino)
156. Processando: Bolo de Banana com Aveia Fitness
157. Processando: Panqueca de banana fit
158. Processando: Bolo de cenoura sem glúten e sem lactose
159. Processando: Pão de micro-ondas

Receitas armazenadas: 159

,Categorias,Título,URL da receita,Tempo de preparo,Nível de dificuldade,Custo,Porções,Ingredientes,Utensílios,Etapas do preparo,Avaliação,Quantidade de avaliações
0,[BOLOS E TORTAS],Bolo de milho de lata no liquidificador,https://www.tudogostoso.com.br/receita/143393-bolo-de-milho-de-lata-no-liquidificador.html,50min,Muito fácil,Custo baixo,1 porção,"[1 lata de milho (sem o líquido), 1 lata de leite (medida da lata de milho), 1 lata de açúcar (m...","[Liquidificador, Pincel de silicone, Espátula de silicone, Formo de bolo, Forno elétrico]","[Escorra o milho e use a própria lata para as medidas., Unte e enfarinhe uma forma de bolo com f...",4.8,1768
1,[BOLOS E TORTAS],Bolo de fubá simples,https://www.tudogostoso.com.br/receita/21560-bolo-de-fuba-simples.html,45min,Fácil,Custo baixo,8 porções,"[3 ovos, 2 xícaras (chá) de açúcar, 2 xícaras (chá) de fubá, 3 colheres (sopa) rasas de farinha ...","[Liquidificador, Copo medidor, Formo de bolo, Prato de sobremesa]","[Bata todos os ingredientes no liquidificador., Coloque em uma forma untada e enfarinhada., Leve...",4.4,1021
2,[BOLOS E TORTAS],Brownie simples e rápido,https://www.tudogostoso.com.br/receita/306823-brownie-simples-e-rapido.html,30min,Fácil,Custo baixo,10 porções,"[5 colheres de manteiga, 3 ovos, 3 xicara de achocolatado, 6 colheres de açúcar, 12 colheres de ...","[Bowl, Espatula, Forma, Fouet, Prato de sobremesa]","[Derreta a manteiga e reserve, Enquanto derrete a manteiga, misture os 3 ovos e a açúcar e mistu...",3.8,623
3,[BOLOS E TORTAS],Bolo simples,https://www.tudogostoso.com.br/receita/29124-bolo-simples.html,40min,Muito fácil,Custo baixo,12 porções,"[2 xícaras (chá) de açúcar, 3 xícaras (chá) de farinha de trigo, 4 colheres (sopa) de margarina,...","[Batedeira, Bowl, Espátula para bolo, Formo de bolo, Prato de sobremesa]","[Bata as claras em neve e reserve., Misture as gemas, a margarina e o açúcar até obter uma massa...",4.7,3787
4,[BOLOS E TORTAS],Bolo de caneca micro-ondas,https://www.tudogostoso.com.br/receita/60429-bolo-de-caneca-micro-ondas.html,10min,Fácil,Custo baixo,1 porção,"[1 ovo, 2 colheres (sopa) de achocolatado em pó, 3 colheres (sopa) rasas de açúcar, 4 colheres (...","[Caneca, Panela, Colher para sobremesa, Luva térmica, Micro-ondas]","[Coloque todos os ingredientes dentro de uma caneca de aproximadamente 300 ml ou mais., Mexa até...",4.4,1796
5,[BOLOS E TORTAS],Bolo de laranja,https://www.tudogostoso.com.br/receita/13953-bolo-de-laranja.html,40min,fácil,Custo baixo,12 porções,"[4 ovos, 2 xícaras (chá) de açúcar, 1 xícara (chá) de óleo, suco de 2 laranjas, casca de 1 laran...","[Liquidificador, Espátula para bolo, Formo de bolo]","[Bata no liquidificador os ovos, o açúcar, o óleo, o suco e a casca da laranja., Passe para uma ...",4.6,742
6,[BOLOS E TORTAS],Bolo pão-de-ló tradicional,https://www.tudogostoso.com.br/receita/142803-bolo-pao-de-lo-tradicional.html,30min,Fácil,Custo baixo,30 porções,"[1 xícara de leite quente, 3 xícaras de farinha de trigo, 2 xícaras de açúcar, 3 gemas, 3 claras...","[Batedeira, Copo medidor, Espátula para bolo, Formo de bolo, Prato de sobremesa]","[Bata as claras em neve até ficar bem consistente., Acrescente o açúcar e as gemas, bata bem., J...",4,237
7,[BOLOS E TORTAS],Bolo de laranja de liquidificador,https://www.tudogostoso.com.br/receita/85429-bolo-de-laranja-de-liquidificador.html,None,Fácil,Custo baixo,10 porções,"[3 ovos, Suco de 2 laranjas, 1 xícara (chá) de óleo, 2 xícaras (chá) de açúcar, 3 xícaras (chá) ...","[Liquidificador, Bowl, Formo de bolo, Fouet]","[Bata no liquidificador os 4 primeiros ingredientes (exceto farinha e fermento), despeje em uma ...",4.7,957
8,[BOLOS E TORTAS],Bolo de iogurte,https://www.tudogostoso.com.br/receita/55080-bolo-de-iogurte.html,50min,Fácil,Custo baixo,12 porções,"[4 ovos, 1 copo de iogurte natural, ½ copo de óleo, 2 copos de açúcar, 2 copos de farinha de tri...","[Forma de pudim, Liquidificador, Copo medidor, Espátula de silicone]","[Bater tudo no liquidificador., Untar uma forma grande de buraco no meio, assar por 40 a 45 minu...",4.7,162
9,[BOLOS E TORTAS],Pavê de chocolate,https://www.tudogostoso.com.br/receita/15939-pave-de-chocolate.html,15min,Fácil,Custo médio,8 porções,"[1 pacote de bolacha maisena, 1/2 copo de leite, 1 colher (sobremesa) de chocolate em pó, 1 lata...","[Batedeira, Panela, Bowl, Espátula de silicone, Travessa de vidro]","[Em uma tigela, misture o leite e o chocolate em pó até que esteja completamente dissolvido., Mo...",4.7,682

## 7. Verificação rápida da coleta

Esta conferência é curta e faz parte da validação do resultado final, sem manter toda a estrutura de logs e diagnóstico da versão anterior.

In [ ]:
if df_receitas.empty:
    print("Nenhuma receita foi coletada.")
else:
    print("URLs duplicadas:", df_receitas["URL da receita"].duplicated().sum())

    resumo_campos = pd.DataFrame({
        "Campo": [
            "Porções",
            "Ingredientes",
            "Utensílios",
            "Etapas do preparo",
            "Avaliação",
        ],
        "Registros preenchidos": [
            df_receitas["Porções"].notna().sum(),
            df_receitas["Ingredientes"].apply(bool).sum(),
            df_receitas["Utensílios"].apply(bool).sum(),
            df_receitas["Etapas do preparo"].apply(bool).sum(),
            df_receitas["Avaliação"].notna().sum(),
        ],
    })

    display(resumo_campos)

    url_teste = (
        "https://www.tudogostoso.com.br/receita/"
        "143393-bolo-de-milho-de-lata-no-liquidificador.html"
    )

    teste = df_receitas[df_receitas["URL da receita"] == url_teste]

    if not teste.empty:
        display(
            teste[
                [
                    "Título",
                    "Categorias",
                    "Porções",
                    "Ingredientes",
                    "Utensílios",
                    "Etapas do preparo",
                    "Avaliação",
                    "Quantidade de avaliações",
                ]
            ]
        )

URLs duplicadas: 0

               Campo  Registros preenchidos
0            Porções                    156
1       Ingredientes                    159
2         Utensílios                    112
3  Etapas do preparo                    159
4          Avaliação                    159

,Título,Categorias,Porções,Ingredientes,Utensílios,Etapas do preparo,Avaliação,Quantidade de avaliações
0,Bolo de milho de lata no liquidificador,[BOLOS E TORTAS],1 porção,"[1 lata de milho (sem o líquido), 1 lata de leite (medida da lata de milho), 1 lata de açúcar (m...","[Liquidificador, Pincel de silicone, Espátula de silicone, Formo de bolo, Forno elétrico]","[Escorra o milho e use a própria lata para as medidas., Unte e enfarinhe uma forma de bolo com f...",4.8,1768

## 8. Campo textual único para PLN

Os campos estruturados continuam separados.

Além deles, criamos `Texto para PLN` reunindo somente:

- porções;
- ingredientes;
- utensílios;
- etapas do preparo.

Esse será o campo usado uma única vez pelo pipeline de pré-processamento.

In [ ]:
def lista_para_texto(valor):
    if isinstance(valor, list):
        return " ".join(str(item) for item in valor if item)
    return "" if pd.isna(valor) else str(valor)


def montar_texto_pln(linha):
    partes = [
        linha["Porções"] or "",
        lista_para_texto(linha["Ingredientes"]),
        lista_para_texto(linha["Utensílios"]),
        lista_para_texto(linha["Etapas do preparo"]),
    ]

    return " ".join(
        parte.strip()
        for parte in partes
        if parte and parte.strip()
    )


df_receitas["Texto para PLN"] = df_receitas.apply(
    montar_texto_pln,
    axis=1,
)

display(
    df_receitas[
        [
            "Título",
            "Porções",
            "Ingredientes",
            "Utensílios",
            "Etapas do preparo",
            "Texto para PLN",
        ]
    ].head(3)
)

,Título,Porções,Ingredientes,Utensílios,Etapas do preparo,Texto para PLN
0,Bolo de milho de lata no liquidificador,1 porção,"[1 lata de milho (sem o líquido), 1 lata de leite (medida da lata de milho), 1 lata de açúcar (m...","[Liquidificador, Pincel de silicone, Espátula de silicone, Formo de bolo, Forno elétrico]","[Escorra o milho e use a própria lata para as medidas., Unte e enfarinhe uma forma de bolo com f...",1 porção 1 lata de milho (sem o líquido) 1 lata de leite (medida da lata de milho) 1 lata de açú...
1,Bolo de fubá simples,8 porções,"[3 ovos, 2 xícaras (chá) de açúcar, 2 xícaras (chá) de fubá, 3 colheres (sopa) rasas de farinha ...","[Liquidificador, Copo medidor, Formo de bolo, Prato de sobremesa]","[Bata todos os ingredientes no liquidificador., Coloque em uma forma untada e enfarinhada., Leve...",8 porções 3 ovos 2 xícaras (chá) de açúcar 2 xícaras (chá) de fubá 3 colheres (sopa) rasas de fa...
2,Brownie simples e rápido,10 porções,"[5 colheres de manteiga, 3 ovos, 3 xicara de achocolatado, 6 colheres de açúcar, 12 colheres de ...","[Bowl, Espatula, Forma, Fouet, Prato de sobremesa]","[Derreta a manteiga e reserve, Enquanto derrete a manteiga, misture os 3 ovos e a açúcar e mistu...",10 porções 5 colheres de manteiga 3 ovos 3 xicara de achocolatado 6 colheres de açúcar 12 colher...

# Parte 2 — Pré-processamento

A partir daqui, a organização segue diretamente a lógica do notebook do professor:

**tokenização → normalização → remoção de stopwords → lematização → stemming**.

O processamento é feito apenas sobre `Texto para PLN`.

## 9. Tokenização

In [ ]:
tokens = [
    word_tokenize(texto, language="portuguese")
    for texto in df_receitas["Texto para PLN"]
]

df_receitas["tokens"] = tokens

display(df_receitas[["Título", "Texto para PLN", "tokens"]].head(3))

,Título,Texto para PLN,tokens
0,Bolo de milho de lata no liquidificador,1 porção 1 lata de milho (sem o líquido) 1 lata de leite (medida da lata de milho) 1 lata de açú...,"[1, porção, 1, lata, de, milho, (, sem, o, líquido, ), 1, lata, de, leite, (, medida, da, lata, ..."
1,Bolo de fubá simples,8 porções 3 ovos 2 xícaras (chá) de açúcar 2 xícaras (chá) de fubá 3 colheres (sopa) rasas de fa...,"[8, porções, 3, ovos, 2, xícaras, (, chá, ), de, açúcar, 2, xícaras, (, chá, ), de, fubá, 3, col..."
2,Brownie simples e rápido,10 porções 5 colheres de manteiga 3 ovos 3 xicara de achocolatado 6 colheres de açúcar 12 colher...,"[10, porções, 5, colheres, de, manteiga, 3, ovos, 3, xicara, de, achocolatado, 6, colheres, de, ..."

## 10. Normalização

Assim como no exemplo do professor, os tokens são convertidos com `casefold()` e permanecem apenas tokens alfabéticos.

Essa etapa também remove a pontuação da representação normalizada.

In [ ]:
def normalizar_tokens(tokens_da_receita):
    return [
        token.casefold()
        for token in tokens_da_receita
        if token.isalpha()
    ]


df_receitas["tokens_normalizados"] = (
    df_receitas["tokens"]
    .apply(normalizar_tokens)
)

display(
    df_receitas[
        ["Título", "tokens", "tokens_normalizados"]
    ].head(3)
)

,Título,tokens,tokens_normalizados
0,Bolo de milho de lata no liquidificador,"[1, porção, 1, lata, de, milho, (, sem, o, líquido, ), 1, lata, de, leite, (, medida, da, lata, ...","[porção, lata, de, milho, sem, o, líquido, lata, de, leite, medida, da, lata, de, milho, lata, d..."
1,Bolo de fubá simples,"[8, porções, 3, ovos, 2, xícaras, (, chá, ), de, açúcar, 2, xícaras, (, chá, ), de, fubá, 3, col...","[porções, ovos, xícaras, chá, de, açúcar, xícaras, chá, de, fubá, colheres, sopa, rasas, de, far..."
2,Brownie simples e rápido,"[10, porções, 5, colheres, de, manteiga, 3, ovos, 3, xicara, de, achocolatado, 6, colheres, de, ...","[porções, colheres, de, manteiga, ovos, xicara, de, achocolatado, colheres, de, açúcar, colheres..."

## 11. Remoção de stopwords

In [ ]:
STOPWORDS_PT = set(stopwords.words("portuguese"))

# Em receitas, "não" e "sem" podem alterar o sentido da instrução.
STOPWORDS_RECEITAS = STOPWORDS_PT - {"não", "nao", "sem"}

def remover_stopwords(tokens_da_receita):
    return [
        token
        for token in tokens_da_receita
        if token not in STOPWORDS_RECEITAS
    ]

df_receitas["tokens_sem_stopwords"] = (
    df_receitas["tokens_normalizados"]
    .apply(remover_stopwords)
)

display(
    df_receitas[
        ["Título", "tokens_normalizados", "tokens_sem_stopwords"]
    ].head(3)
)

,Título,tokens_normalizados,tokens_sem_stopwords
0,Bolo de milho de lata no liquidificador,"[porção, lata, de, milho, sem, o, líquido, lata, de, leite, medida, da, lata, de, milho, lata, d...","[porção, lata, milho, sem, líquido, lata, leite, medida, lata, milho, lata, açúcar, medida, lata..."
1,Bolo de fubá simples,"[porções, ovos, xícaras, chá, de, açúcar, xícaras, chá, de, fubá, colheres, sopa, rasas, de, far...","[porções, ovos, xícaras, chá, açúcar, xícaras, chá, fubá, colheres, sopa, rasas, farinha, trigo,..."
2,Brownie simples e rápido,"[porções, colheres, de, manteiga, ovos, xicara, de, achocolatado, colheres, de, açúcar, colheres...","[porções, colheres, manteiga, ovos, xicara, achocolatado, colheres, açúcar, colheres, farinha, t..."

## 12. Lematização

In [ ]:
def lematizar(tokens_da_receita):
    texto_processavel = " ".join(tokens_da_receita)
    documento = nlp(texto_processavel)
    return [token.lemma_ for token in documento]


df_receitas["lemas"] = (
    df_receitas["tokens_sem_stopwords"]
    .apply(lematizar)
)

display(
    df_receitas[
        ["Título", "tokens_sem_stopwords", "lemas"]
    ].head(3)
)

,Título,tokens_sem_stopwords,lemas
0,Bolo de milho de lata no liquidificador,"[porção, lata, milho, sem, líquido, lata, leite, medida, lata, milho, lata, açúcar, medida, lata...","[porção, lato, milho, sem, líquido, lato, leite, medida, lato, milho, lato, açúcar, medida, lato..."
1,Bolo de fubá simples,"[porções, ovos, xícaras, chá, açúcar, xícaras, chá, fubá, colheres, sopa, rasas, farinha, trigo,...","[porção, ovo, xícara, chá, açúcar, xícara, chá, fubá, colher, sopa, raso, Farinha, trigo, copo, ..."
2,Brownie simples e rápido,"[porções, colheres, manteiga, ovos, xicara, achocolatado, colheres, açúcar, colheres, farinha, t...","[porção, colher, manteiga, ovo, xicara, achocolatar, colher, açúcar, colher, farinho, trigo, bow..."

## 13. Stemming

In [ ]:
stemmer = RSLPStemmer()


def aplicar_stemming(tokens_da_receita):
    return [
        stemmer.stem(token)
        for token in tokens_da_receita
    ]


df_receitas["stems"] = (
    df_receitas["tokens_sem_stopwords"]
    .apply(aplicar_stemming)
)

display(
    df_receitas[
        ["Título", "tokens_sem_stopwords", "stems"]
    ].head(3)
)

,Título,tokens_sem_stopwords,stems
0,Bolo de milho de lata no liquidificador,"[porção, lata, milho, sem, líquido, lata, leite, medida, lata, milho, lata, açúcar, medida, lata...","[porç, lat, milh, sem, líqu, lat, leit, med, lat, milh, lat, açúc, med, lat, milh, lat, floc, mi..."
1,Bolo de fubá simples,"[porções, ovos, xícaras, chá, açúcar, xícaras, chá, fubá, colheres, sopa, rasas, farinha, trigo,...","[porç, ovo, xíc, chá, açúc, xíc, chá, fub, colh, sop, ras, far, trig, cop, americ, óle, cop, lei..."
2,Brownie simples e rápido,"[porções, colheres, manteiga, ovos, xicara, achocolatado, colheres, açúcar, colheres, farinha, t...","[porç, colh, manteig, ovo, xic, achocolat, colh, açúc, colh, far, trig, bowl, espatul, form, fou..."

## 14. Pipeline completo com Pandas

Esta função reúne as mesmas etapas, seguindo o formato demonstrado pelo professor.

In [ ]:
def processar_texto(texto):
    tokens_locais = word_tokenize(
        texto,
        language="portuguese"
    )
    normalizados_locais = normalizar_tokens(tokens_locais)
    sem_stopwords_locais = remover_stopwords(
        normalizados_locais
    )

    return pd.Series({
        "tokens_pipeline": tokens_locais,
        "tokens_normalizados_pipeline": normalizados_locais,
        "tokens_sem_stopwords_pipeline": sem_stopwords_locais,
        "lemas_pipeline": lematizar(sem_stopwords_locais),
        "stems_pipeline": aplicar_stemming(sem_stopwords_locais),
    })


colunas_processadas = (
    df_receitas["Texto para PLN"]
    .apply(processar_texto)
)

df_processado = pd.concat(
    [df_receitas, colunas_processadas],
    axis=1,
)

pd.set_option("display.max_colwidth", 100)
display(df_processado.head())

,Categorias,Título,URL da receita,Tempo de preparo,Nível de dificuldade,Custo,Porções,Ingredientes,Utensílios,Etapas do preparo,...,tokens,tokens_normalizados,tokens_sem_stopwords,lemas,stems,tokens_pipeline,tokens_normalizados_pipeline,tokens_sem_stopwords_pipeline,lemas_pipeline,stems_pipeline
0,[BOLOS E TORTAS],Bolo de milho de lata no liquidificador,https://www.tudogostoso.com.br/receita/143393-bolo-de-milho-de-lata-no-liquidificador.html,50min,Muito fácil,Custo baixo,1 porção,"[1 lata de milho (sem o líquido), 1 lata de leite (medida da lata de milho), 1 lata de açúcar (m...","[Liquidificador, Pincel de silicone, Espátula de silicone, Formo de bolo, Forno elétrico]","[Escorra o milho e use a própria lata para as medidas., Unte e enfarinhe uma forma de bolo com f...",...,"[1, porção, 1, lata, de, milho, (, sem, o, líquido, ), 1, lata, de, leite, (, medida, da, lata, ...","[porção, lata, de, milho, sem, o, líquido, lata, de, leite, medida, da, lata, de, milho, lata, d...","[porção, lata, milho, sem, líquido, lata, leite, medida, lata, milho, lata, açúcar, medida, lata...","[porção, lato, milho, sem, líquido, lato, leite, medida, lato, milho, lato, açúcar, medida, lato...","[porç, lat, milh, sem, líqu, lat, leit, med, lat, milh, lat, açúc, med, lat, milh, lat, floc, mi...","[1, porção, 1, lata, de, milho, (, sem, o, líquido, ), 1, lata, de, leite, (, medida, da, lata, ...","[porção, lata, de, milho, sem, o, líquido, lata, de, leite, medida, da, lata, de, milho, lata, d...","[porção, lata, milho, sem, líquido, lata, leite, medida, lata, milho, lata, açúcar, medida, lata...","[porção, lato, milho, sem, líquido, lato, leite, medida, lato, milho, lato, açúcar, medida, lato...","[porç, lat, milh, sem, líqu, lat, leit, med, lat, milh, lat, açúc, med, lat, milh, lat, floc, mi..."
1,[BOLOS E TORTAS],Bolo de fubá simples,https://www.tudogostoso.com.br/receita/21560-bolo-de-fuba-simples.html,45min,Fácil,Custo baixo,8 porções,"[3 ovos, 2 xícaras (chá) de açúcar, 2 xícaras (chá) de fubá, 3 colheres (sopa) rasas de farinha ...","[Liquidificador, Copo medidor, Formo de bolo, Prato de sobremesa]","[Bata todos os ingredientes no liquidificador., Coloque em uma forma untada e enfarinhada., Leve...",...,"[8, porções, 3, ovos, 2, xícaras, (, chá, ), de, açúcar, 2, xícaras, (, chá, ), de, fubá, 3, col...","[porções, ovos, xícaras, chá, de, açúcar, xícaras, chá, de, fubá, colheres, sopa, rasas, de, far...","[porções, ovos, xícaras, chá, açúcar, xícaras, chá, fubá, colheres, sopa, rasas, farinha, trigo,...","[porção, ovo, xícara, chá, açúcar, xícara, chá, fubá, colher, sopa, raso, Farinha, trigo, copo, ...","[porç, ovo, xíc, chá, açúc, xíc, chá, fub, colh, sop, ras, far, trig, cop, americ, óle, cop, lei...","[8, porções, 3, ovos, 2, xícaras, (, chá, ), de, açúcar, 2, xícaras, (, chá, ), de, fubá, 3, col...","[porções, ovos, xícaras, chá, de, açúcar, xícaras, chá, de, fubá, colheres, sopa, rasas, de, far...","[porções, ovos, xícaras, chá, açúcar, xícaras, chá, fubá, colheres, sopa, rasas, farinha, trigo,...","[porção, ovo, xícara, chá, açúcar, xícara, chá, fubá, colher, sopa, raso, Farinha, trigo, copo, ...","[porç, ovo, xíc, chá, açúc, xíc, chá, fub, colh, sop, ras, far, trig, cop, americ, óle, cop, lei..."
2,[BOLOS E TORTAS],Brownie simples e rápido,https://www.tudogostoso.com.br/receita/306823-brownie-simples-e-rapido.html,30min,Fácil,Custo baixo,10 porções,"[5 colheres de manteiga, 3 ovos, 3 xicara de achocolatado, 6 colheres de açúcar, 12 colheres de ...","[Bowl, Espatula, Forma, Fouet, Prato de sobremesa]","[Derreta a manteiga e reserve, Enquanto derrete a manteiga, misture os 3 ovos e a açúcar e mistu...",...,"[10, porções, 5, colheres, de, manteiga, 3, ovos, 3, xicara, de, achocolatado, 6, colheres, de, ...","[porções, colheres, de, manteiga, ovos, xicara, de, achocolatado, colheres, de, açúcar, colheres...","[porções, colheres, manteiga, ovos, xicara, achocolatado, colheres, açúcar, colheres, farinha, t...","[porção, colher, manteiga, ovo, xicara, achocolatar, colher, açúcar, colher, farinho, trigo, bow...","[porç, colh, manteig, ovo, xic, achocolat, colh, açúc, colh, far, trig, bowl, espatul, form, fou...","[10, porções, 5, colheres, de, manteiga, 3, ovos, 3, xicara, de, achocolatado, 6, colheres, de, ...","[porções, colheres, de, manteiga, ovos, xicara, de, achocolatado, colheres, de, açúcar, colheres...","[porções, colheres, manteiga, ovos, xicara, achocolatado, colheres, açúcar, colheres, farinha, t...","[porção, colher, manteiga, ovo, xicara, achocolatar, colher, açúcar, colher, farinho, trigo, bow...","[porç, colh, manteig, ovo, xic, achocolat, colh, açúc, colh, far, trig, bowl, espatul, form, fou..."
3,[BOLOS E TORTAS],Bolo simples,https://www.tudogostoso.com.br/receita/29124-bolo-simples.html,40min,Muito fácil,Custo baixo,12 porções,"[2 xícaras (chá) de açúcar, 3 xícaras (chá) de farinha de trigo, 4 colheres (sopa) de margarina,...","[Batedeira, Bowl, Espátula para bolo, Formo de bolo, Prato de sobremesa]","[Bata as claras em neve e reserve., Misture as gemas, a margarina e o açúcar até obter uma massa...",...,"[12, porções, 2, xícaras, (, chá, ), de, açúcar, 3, xícaras, (, chá, ), de, farinha, de, trigo, ...","[porções, xícaras, chá, de, açúcar, xícaras, chá, de, farinha, de, trigo, colheres, sopa, de, ma...","[porções, xícaras, chá, açúcar, xícaras, chá, farinha, trigo, colheres, sopa, margarina, ovos, x...","[porção, xícaro, chá, açúcar, xícara, chá, Farinha, trigo, colher, sopa, margarinar, ovo, xícara...","[porç, xíc, chá, açúc, xíc, chá, far, trig, colh, sop, margarin, ovo, xíc, chá, leit, colh, sop,...","[12, porções, 2, xícaras, (, chá, ), de, açúcar, 3, xícaras, (, chá, ), de, farinha, de, trigo, ...","[porções, xícaras, chá, de, açúcar, xícaras, chá, de, farinha, de, trigo, colheres, sopa, de, ma...","[porções, xícaras, chá, açúcar, xícaras, chá, farinha, trigo, colheres, sopa, margarina, ovos, x...","[porção, xícaro, chá, açúcar, xícara, chá, Farinha, trigo, colher, sopa, margarinar, ovo, xícara...","[porç, xíc, chá, açúc, xíc, chá, far, trig, colh, sop, margarin, ovo, xíc, chá, leit, colh, sop,..."
4,[BOLOS E TORTAS],Bolo de caneca micro-ondas,https://www.tudogostoso.com.br/receita/60429-bolo-de-caneca-micro-ondas.html,10min,Fácil,Custo baixo,1 porção,"[1 ovo, 2 colheres (sopa) de achocolatado em pó, 3 colheres (sopa) rasas de açúcar, 4 colheres (...","[Caneca, Panela, Colher para sobremesa, Luva térmica, Micro-ondas]","[Coloque todos os ingredientes dentro de uma caneca de aproximadamente 300 ml ou mais., Mexa até...",...,"[1, porção, 1, ovo, 2, colheres, (, sopa, ), de, achocolatado, em, pó, 3, colheres, (, sopa, ), ...","[porção, ovo, colheres, sopa, de, achocolatado, em, pó, colheres, sopa, rasas, de, açúcar, colhe...","[porção, ovo, colheres, sopa, achocolatado, pó, colheres, sopa, rasas, açúcar, colheres, sopa, r...","[porção, ovo, colher, sopa, achocolatar, pó, colher, sopa, rasa, açúcar, colher, sopa, raso, Far...","[porç, ovo, colh, sop, achocolat, pó, colh, sop, ras, açúc, colh, sop, ras, far, trig, colh, sop...","[1, porção, 1, ovo, 2, colheres, (, sopa, ), de, achocolatado, em, pó, 3, colheres, (, sopa, ), ...","[porção, ovo, colheres, sopa, de, achocolatado, em, pó, colheres, sopa, rasas, de, açúcar, colhe...","[porção, ovo, colheres, sopa, achocolatado, pó, colheres, sopa, rasas, açúcar, colheres, sopa, r...","[porção, ovo, colher, sopa, achocolatar, pó, colher, sopa, rasa, açúcar, colher, sopa, raso, Far...","[porç, ovo, colh, sop, achocolat, pó, colh, sop, ras, açúc, colh, sop, ras, far, trig, colh, sop..."

## 15. Exportação

A saída contém:

- campos originais da receita;
- lista de categorias;
- campo textual consolidado;
- representações geradas pelo pré-processamento.

In [ ]:
df_processado.to_csv(
    "receitas_tudogostoso_processadas.csv",
    index=False,
    encoding="utf-8-sig",
)

print("Arquivo gerado: receitas_tudogostoso_processadas.csv")

Arquivo gerado: receitas_tudogostoso_processadas.csv